name: zapato
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  carousel_slider: ^4.2.1
  flutter_typeahead: ^5.2.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.0
  animations: ^2.0.7
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  intl: ^0.18.1  # ✅ ya está aquí correctamente
  image_picker: ^1.0.4
  connectivity_plus: ^5.0.2
  sqflite: any
  path: any
  path_provider: ^2.0.14
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/explosion.mp3
    - assets/avatar.png
